name: Entrega continua

on:
  workflow_call:

jobs:

  EC2:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
    # Artifact name
        name: programa
    - uses: actions/checkout@v4.1.7
    
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # EC2_SSH_KEY is better
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # "ec2-3-34-33-67.us-east-2.compute.amazonaws.com"
        REMOTE_USER: ${{ secrets.REMOTE_USER }} # "ec2-user"
        TARGET: /home/${{ secrets.REMOTE_USER }} #/home/ec2-user
        EXCLUDE: "postgres-data"
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export DBHOST=${{ secrets.DBHOST }}
          export DBUSER=${{ secrets.DBUSER }}
          export DBPASSWORD=${{ secrets.DBPASSWORD }}
          export DBNAME=${{ secrets.DBNAME }}
          export DBPORT=${{ secrets.DBPORT }}
          export PORT=8000
          chmod +x main
          nohup ./main > nohup.out 2> nohup.err < /dev/null &
        
        
